export interface Video {
  id: string;
  thumb: string;
  title: string;
  dur: string;
  lang: string;
  age: string;
  grp: string;
  tag1: string;
  tag2: string;
  url: string;
  source: string;
  body: string;
}

export const VIDEOS: Video[] = [
  {
    id: "AQRDLBrWr0E",
    thumb: "https://img.youtube.com/vi/AQRDLBrWr0E/maxresdefault.jpg",
    title: "Setting up parental controls on a phone",
    dur: "3:08",
    lang: "English",
    age: "For parents",
    grp: "parents",
    tag1: "Parental controls",
    tag2: "Step by step",
    url: "https://youtu.be/AQRDLBrWr0E",
    source: "YouTube creator",
    body: "A calm walk-through for Android — restrict what they can reach, set a screen-time limit, and see which apps they actually use. Fifteen minutes of setup, done once.",
  },
  {
    id: "mKC79A-R2HQ",
    thumb: "https://img.youtube.com/vi/mKC79A-R2HQ/sddefault.jpg",
    title: "Understanding and preventing cyberbullying",
    dur: "6:07",
    lang: "English",
    age: "Ages 10–13",
    grp: "10",
    tag1: "Bullying",
    tag2: "What to do",
    url: "https://youtu.be/mKC79A-R2HQ",
    source: "YouTube creator",
    body: "What bullying looks like on a group chat, how to spot it when your child will not say it out loud, and the steps that actually stop it. With examples from Indian schools.",
  },
  {
    id: "d5kW4pI_VQw",
    thumb: "https://img.youtube.com/vi/d5kW4pI_VQw/maxresdefault.jpg",
    title: "Online safety basics, explained for kids",
    dur: "5:23",
    lang: "Hindi",
    age: "Ages 6–9",
    grp: "6",
    tag1: "Safety basics",
    tag2: "Watch together",
    url: "https://www.youtube.com/watch?v=d5kW4pI_VQw",
    source: "YouTube creator",
    body: "Simple enough for a six-year-old: which sites are safe, what you never share, and when to come and tell a grown-up. Good to watch sitting next to them.",
  },
  {
    id: "BcdZm3WAF4A",
    thumb: "https://img.youtube.com/vi/BcdZm3WAF4A/maxresdefault.jpg",
    title: "Your digital footprint: think before you post",
    dur: "1:28",
    lang: "English",
    age: "Ages 14–18",
    grp: "14",
    tag1: "Digital footprint",
    tag2: "Social media",
    url: "https://youtu.be/BcdZm3WAF4A",
    source: "YouTube creator",
    body: "For teenagers: why a post from today can still be around at a job interview, and how to keep a version of yourself online you will not wince at later.",
  },
  // TODO(neil): confirm the real id for this one. '0RjRtMWYres' (from the old build) serves no
  // thumbnail and looks unavailable; '4JzGJ_hn7k0' is live, so the item points wholly at that.
  {
    id: "4JzGJ_hn7k0",
    thumb: "https://img.youtube.com/vi/4JzGJ_hn7k0/maxresdefault.jpg",
    title: "Staying safe in online games",
    dur: "1:07",
    lang: "English",
    age: "Ages 10–13",
    grp: "10",
    tag1: "Gaming",
    tag2: "Roblox & PUBG",
    url: "https://www.youtube.com/watch?v=4JzGJ_hn7k0",
    source: "YouTube creator",
    body: "In-game purchases, voice chat with strangers, and the pressure to keep playing. What to turn off in Roblox and PUBG, and what to say about the rest.",
  },
  {
    id: "kUyQI0USNSY",
    thumb: "https://img.youtube.com/vi/kUyQI0USNSY/maxresdefault.jpg",
    title: "A common sense approach to internet safety",
    dur: "4:00",
    lang: "English",
    age: "For parents",
    grp: "parents",
    tag1: "Safety basics",
    tag2: "Parental controls",
    url: "https://www.youtube.com/watch?v=kUyQI0USNSY",
    source: "Google & Common Sense Media",
    body: "Made with Google and Common Sense Media: plain-language ground rules for families — what to teach before handing over a device, and what to watch for after.",
  },
  {
    id: "uflAbX9j8Xg",
    thumb: "https://img.youtube.com/vi/uflAbX9j8Xg/maxresdefault.jpg",
    title: "Ending online abuse",
    dur: "1:47",
    lang: "English",
    age: "For parents",
    grp: "parents",
    tag1: "Grooming",
    tag2: "Online abuse",
    url: "https://www.youtube.com/watch?v=uflAbX9j8Xg",
    source: "NSPCC",
    body: "How grooming can start with a friendly stranger online, the warning signs an adult should not ignore, and how to talk to your child without making them feel blamed. If it has already happened, CHILDLINE India (1098) and cybercrime.gov.in take it from here.",
  },
  {
    id: "M8yoRrq2tUg",
    thumb: "https://img.youtube.com/vi/M8yoRrq2tUg/sddefault.jpg",
    title: "How to tackle bullying",
    dur: "2:12",
    lang: "English",
    age: "Ages 10–13",
    grp: "10",
    tag1: "Bullying",
    tag2: "What to do",
    url: "https://www.youtube.com/watch?v=M8yoRrq2tUg",
    source: "NSPCC",
    body: "A short, practical look at what actually helps a child being bullied — believing them first, then acting. The same steps apply whether it starts at school or in a group chat.",
  },
  {
    id: "cgToaBQqXlI",
    thumb: "https://img.youtube.com/vi/cgToaBQqXlI/maxresdefault.jpg",
    title: "Be Internet Awesome, with Google",
    dur: "1:32",
    lang: "English",
    age: "Ages 6–9",
    grp: "6",
    tag1: "Safety basics",
    tag2: "Digital citizenship",
    url: "https://www.youtube.com/watch?v=cgToaBQqXlI",
    source: "Google",
    body: "Google's five simple rules for young kids going online for the first time — smart, alert, strong, kind, and brave. A good one to watch together before handing over a device.",
  },
  {
    id: "i307esUZTSc",
    thumb: "https://img.youtube.com/vi/i307esUZTSc/maxresdefault.jpg",
    title: "Be Internet Awesome",
    dur: "1:05",
    lang: "English",
    age: "Ages 10–13",
    grp: "10",
    tag1: "Digital citizenship",
    tag2: "Safety basics",
    url: "https://www.youtube.com/watch?v=i307esUZTSc",
    source: "Google",
    body: "Why being a good digital citizen matters as much as being a safe one — respecting others online, thinking before sharing, and making smart calls without a parent watching every move.",
  },
  {
    id: "9Q4pxdUimAU",
    thumb: "https://img.youtube.com/vi/9Q4pxdUimAU/maxresdefault.jpg",
    title: "It's called sextortion",
    dur: "2:04",
    lang: "English",
    age: "Ages 14–18",
    grp: "14",
    tag1: "Sextortion",
    tag2: "Red flags",
    url: "https://www.youtube.com/watch?v=9Q4pxdUimAU",
    source: "NCMEC",
    body: "How sextortion scams usually start, the red flags before the blackmail begins, and why being an upstander for a friend matters. Never pay, never send more — report to cybercrime.gov.in or call 1098.",
  },
];

// The home page "Watch and learn" carousel rotates through the first three.
export const FEATURED_VIDEOS = VIDEOS.slice(0, 3);
